// Erzeugt aus einer gerenderten HTML-Signatur die drei Dateien, die Outlook erwartet:
//   <name>.htm  — Haupt-Signatur (HTML-Mails)
//   <name>.txt  — Plain-Text-Variante (TXT-Mails)
//   <name>.rtf  — RTF-Variante (RTF-Mails, selten)
// Plus optional Bilder in <name>_files/.

const HTML_ENTITY_MAP = {
  '&nbsp;': ' ', '&amp;': '&', '&lt;': '<', '&gt;': '>',
  '&quot;': '"', '&apos;': "'", '&#39;': "'",
};

function decodeEntities(s) {
  return s.replace(/&[a-z]+;|&#\d+;/gi, m => {
    if (HTML_ENTITY_MAP[m]) return HTML_ENTITY_MAP[m];
    const dec = m.match(/^&#(\d+);$/);
    if (dec) return String.fromCharCode(parseInt(dec[1], 10));
    return m;
  });
}

// Plain-Text aus HTML extrahieren.
export function htmlToText(html) {
  if (!html) return '';
  return decodeEntities(
    html
      .replace(/<\s*br\s*\/?>/gi, '\n')
      .replace(/<\s*\/\s*(p|div|tr|li|h[1-6])\s*>/gi, '\n')
      .replace(/<[^>]+>/g, '')
  )
    .replace(/[ \t]+\n/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

// data:image/<type>;base64,<data> -> Buffer + Extension
function parseDataUri(uri) {
  const m = uri.match(/^data:image\/([a-zA-Z0-9+]+);base64,(.+)$/);
  if (!m) return null;
  return { ext: m[1].toLowerCase().replace('jpeg', 'jpg'), data: Buffer.from(m[2], 'base64') };
}

// Extrahiert data:-Image-URIs, ersetzt durch relative Pfade <name>_files/imageNNN.<ext>.
function extractInlineImages(html, signatureName) {
  const images = [];
  let counter = 0;
  const replaced = html.replace(/(<img\b[^>]*\bsrc=)(["'])(data:image\/[^"']+)\2/gi, (_, head, q, uri) => {
    const parsed = parseDataUri(uri);
    if (!parsed) return `${head}${q}${uri}${q}`;
    counter += 1;
    const remoteName = `image${String(counter).padStart(3, '0')}.${parsed.ext}`;
    images.push({ remoteName, buffer: parsed.data });
    return `${head}${q}${signatureName}_files/${remoteName}${q}`;
  });
  return { html: replaced, images };
}

// HTML in Outlook-kompatiblen Document-Wrapper packen.
function wrapHtmlDocument(bodyHtml, signatureName) {
  const safeName = signatureName.replace(/[<>&"]/g, '');
  return `<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="Generator" content="M365 Signature Manager">
<title>${safeName}</title>
<style>
body { font-family: Calibri, Arial, sans-serif; font-size: 11pt; }
</style>
</head>
<body lang="DE-DE">
${bodyHtml}
</body>
</html>
`;
}

// Minimales RTF: Header + escaped Plain Text.
function buildRtf(plainText) {
  const escaped = (plainText || '')
    .replace(/\\/g, '\\\\')
    .replace(/\{/g, '\\{')
    .replace(/\}/g, '\\}')
    .split('\n').join('\\par\n');
  return `{\\rtf1\\ansi\\ansicpg1252\\deff0\\nouicompat{\\fonttbl{\\f0\\fnil\\fcharset0 Calibri;}}
{\\colortbl ;\\red0\\green0\\blue0;}
\\viewkind4\\uc1\\pard\\sa200\\sl276\\slmult1\\f0\\fs22 ${escaped}\\par
}`;
}

// CMD-Skript fuer den User-Startup-Ordner. Setzt unsere Signatur als Outlook-Standard
// (neue Mail + Antwort/Weiterleitung) und deaktiviert das Cloud-Roaming, damit Outlook
// die lokal deployte .htm tatsaechlich verwendet. Idempotent bei jedem Login.
//
// Reihenfolge ist wichtig:
// 1) Outlook hart beenden — ein laufender Outlook hat den Cloud-Sync-Thread schon
//    initialisiert und holt die alte Signatur zurueck, bevor DisableRoamingSignatures
//    wirksam wird. Beim Login meist no-op, schadet aber nicht.
// 2) Cloud-Roaming deaktivieren — MUSS vor NewSignature passieren, sonst syncen die
//    Cloud-Files unsere lokalen .htm weg.
// 3) NewSignature / ReplySignature auf den deployten Namen setzen.
export function buildSetDefaultSignatureScript(signatureName) {
  // Anfuehrungszeichen im Signatur-Namen wuerden den reg-add-Aufruf brechen.
  const safe = (signatureName || 'Firma_Standard').replace(/["']/g, '');
  const lines = [
    '@echo off',
    'REM Auto-generated by M365 Signature Manager - wird beim naechsten Deploy ueberschrieben.',
    'REM Schritt 1: Outlook hart beenden (sonst behaelt der laufende Roaming-Sync die alte Signatur).',
    'taskkill /im OUTLOOK.EXE /f >nul 2>&1',
    'taskkill /im olk.exe /f >nul 2>&1',
    'REM Schritt 2: Cloud-Roaming deaktivieren - MUSS vor NewSignature passieren.',
    'reg add "HKCU\\Software\\Microsoft\\Office\\16.0\\Outlook\\Setup" /v DisableRoamingSignatures /t REG_DWORD /d 1 /f >nul 2>&1',
    'reg add "HKCU\\Software\\Microsoft\\Office\\16.0\\Outlook\\Setup" /v DisableRoamingSignaturesTemporaryToggle /t REG_DWORD /d 1 /f >nul 2>&1',
    'REM Schritt 3: Default-Signatur fuer neue Mails und Antworten/Weiterleitungen.',
    `reg add "HKCU\\Software\\Microsoft\\Office\\16.0\\Common\\MailSettings" /v NewSignature /t REG_SZ /d "${safe}" /f >nul 2>&1`,
    `reg add "HKCU\\Software\\Microsoft\\Office\\16.0\\Common\\MailSettings" /v ReplySignature /t REG_SZ /d "${safe}" /f >nul 2>&1`,
    'exit /b 0',
    '',
  ];
  // Windows-CMD will CRLF.
  return lines.join('\r\n');
}

// Haupt-Funktion: erzeugt alle Outlook-Signatur-Dateien aus gerendertem HTML.
// Liefert { htm: string, txt: string, rtf: string, images: [{remoteName, buffer}] }
export function generateSignatureFiles(renderedHtml, signatureName) {
  const { html: htmlWithFileRefs, images } = extractInlineImages(renderedHtml || '', signatureName);
  const htm = wrapHtmlDocument(htmlWithFileRefs, signatureName);
  const txt = htmlToText(renderedHtml || '');
  const rtf = buildRtf(txt);
  return { htm, txt, rtf, images };
}
